# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Honors_Awards',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Interests',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Skills',
        ),
        migrations.AlterField(
            model_name='info',
            name='About',
            field=models.TextField(),
        ),
    ]
