# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160630_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
