# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160630_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school',
        ),
        migrations.AddField(
            model_name='education',
            name='College',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='School',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='info',
            name='Education',
            field=models.ManyToManyField(to='students.education', verbose_name='Education'),
        ),
    ]
