# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20160630_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='honors_awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honors_awards', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='Courses',
            field=models.ManyToManyField(to='students.courses', verbose_name='Courses'),
        ),
        migrations.AddField(
            model_name='info',
            name='Experience',
            field=models.ManyToManyField(to='students.experience', verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='info',
            name='Honors_Awards',
            field=models.ManyToManyField(to='students.honors_awards', verbose_name='Honors_Awards'),
        ),
        migrations.AddField(
            model_name='info',
            name='Interests',
            field=models.ManyToManyField(to='students.interests', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='info',
            name='Projects',
            field=models.ManyToManyField(to='students.projects', verbose_name='Projects'),
        ),
        migrations.AddField(
            model_name='info',
            name='Skills',
            field=models.ManyToManyField(to='students.skills', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='info',
            name='Test_Scores',
            field=models.ManyToManyField(to='students.scores', verbose_name='Test_Scores'),
        ),
    ]
