# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20160630_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Honors_Awards',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Interests',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Test_Scores',
        ),
        migrations.AddField(
            model_name='education',
            name='Info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.Info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='About',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Course',
            field=models.CharField(blank=True, choices=[('ipg', 'IPG'), ('mtech', 'MTECH'), ('mba', 'MBA'), ('phd', 'PHD')], default='ipg', max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='Education',
            field=models.ManyToManyField(blank=True, to='students.education', verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='info',
            name='Email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='Name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='Pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='Roll',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='Website',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='experience',
        ),
        migrations.DeleteModel(
            name='honors_awards',
        ),
        migrations.DeleteModel(
            name='interests',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='scores',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
    ]
