# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160701_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Info',
        ),
        migrations.AddField(
            model_name='info',
            name='Courses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Honors_Awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Test_Scores',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='info',
            name='Education',
        ),
        migrations.AddField(
            model_name='info',
            name='Education',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='education',
        ),
    ]
