# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_auto_20160701_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='Course',
            field=models.CharField(choices=[('ipg', 'IPG'), ('mtech', 'MTECH'), ('mba', 'MBA'), ('phd', 'PHD')], default='ipg', max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='Name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='Roll',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='Test_Scores',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
