# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20160708_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='info',
            unique_together=set([('user', 'Name', 'Roll')]),
        ),
    ]
