# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20160708_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='submit',
        ),
        migrations.AddField(
            model_name='info',
            name='Year',
            field=models.CharField(choices=[('first', 'FIRST'), ('second', 'SECOND'), ('third', 'THIRD'), ('fourth', 'FOURTH'), ('fifth', 'FIFTH')], default='first', max_length=10),
        ),
    ]
