# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20160710_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='Year',
        ),
    ]
