# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_info_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Year',
            field=models.CharField(choices=[('first', 'FIRST'), ('second', 'SECOND'), ('third', 'THIRD'), ('fourth', 'FOURTH'), ('fifth', 'FIFTH')], default='first', max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
