# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20160710_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='About',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Courses',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Education',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Experience',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Honors_Awards',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Projects',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Skills',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Test_Scores',
            field=tinymce.models.HTMLField(blank=True, max_length=1000),
        ),
    ]
