# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:21
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20160714_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='About',
            field=redactor.fields.RedactorField(),
        ),
    ]
