# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20160714_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='DOB',
            field=models.DateField(default=True),
        ),
    ]
