# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20160716_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='DOB',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
