# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_remove_info_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='DOB',
            field=models.DateField(auto_now=True, default=datetime.date(2016, 7, 16)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='About',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
