# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_auto_20160719_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
