# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_auto_20160719_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='DOB',
            field=models.DateField(blank=True, default='<built-in method today of type object at 0x000000006E30B880>'),
        ),
    ]
