# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 17:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_remove_info_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Test_Scores',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
