# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_auto_20160728_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='About',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Courses',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Education',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Email',
            field=models.EmailField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='Experience',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Honors_Awards',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Projects',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Skills',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Test_Scores',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='info',
            name='Website',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
